typography_spectrum: 0.7953692
color:
  lightness: 0.7665832
  brandStrength: 0.9693367
  saturation: 0.3685857
  rhythmicContrast: 0.889223
  brandColors:
    - '#F5F4F6'
    - '#D1D8D2'
    - '#090000'
    - '#453C49'
    - '#670F17'
layout_spectrum: 1
name: Sebastian-kaye
title: 'Media Art & Design '
